nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['http://localhost:3000', 'https://backend.ddev.site']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600
    expose_headers: ['Link', 'X-Total-Count']